### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by UltiRequiem** [kuator/kuator.github.io#1]
Very cool page

**Comment by kuator** [comment]
You can open a pr, I don't know how to add a license

**Comment by kuator** [comment]
> Very cool page

Thanks

**Comment by kuator** [comment]
Fixed

**Comment by kuator** [comment]
> Very cool page

Btw, check this out: https://kuator.github.io/gh-pages/image-reveal-kinda/
I spent three days on it

**Comment by UltiRequiem** [comment]
It's also pretty cool, but I liked this one more:
https://kuator.github.io/gh-pages/cloudmoon
